#symfony
z-symfony-docker:
  image: iamluc/symfony
  ports:
    - 80:80
  volumes:
    - ./:/var/www/html
  links:
    - database

#phpmyadmin
phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  environment:
    - PMA_ARBITRARY=1
    - MYSQL_ROOT_PASSWORD=your_password
    - PMA_HOST=database
    - PMA_USER=your_user
    - PMA_PASSWORD=your_password
  restart: always
  ports:
    - 8080:80
  links:
    - database

#mysql
database:
  build: docker/mysql
  ports:
   - "3306:3306"  
  environment:
     - MYSQL_ROOT_PASSWORD=your_password
     - MYSQL_DATABASE=your_data_base
     - MYSQL_USER=your_user
     - MYSQL_PASSWORD=your_password
  volumes:
    - /var/lib/mysql:/var/lib/mysql